build: add pthread dependency to LDFLAGS
libuv has a dependency on pthread which doesn't seem to get picked
up through any other configure steps. The errors returned during
linking are:

libuv.a(libuv_la-thread.o): undefined reference to symbol 'pthread_rwlock_trywrlock@@GLIBC_2.2.5'
libpthread.so.0: error adding symbols: DSO missing from command line